# Generated by Django 2.2 on 2021-01-24 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallpost',
            name='user',
        ),
        migrations.AddField(
            model_name='wallpost',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='WallOwner', to='DashboardApp.User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wallpost',
            name='poster',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='WallPostAuthor', to='DashboardApp.User'),
            preserve_default=False,
        ),
    ]
